
virtuesJson = [
{
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "cardBody": "You gain +1 Max Morale. <br> <br> Whenever you <strong> Surge, </strong> you may choose to <strong> Surge </strong> recklessly. If you do, then you gain an extra +1 <strong> Force </strong> for each <strong> Focus </strong> spent to <strong> Surge, </strong> but you also gain -1 <strong> Composure </strong> for each <strong> Focus </strong> spent. The </strong> Composure </strong> penalty expires at the start of your next turn.",
            "cardTooltip": "+1 <strong> Morale. </strong> You can <strong> Surge </strong> recklessly."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Other heroes gain <strong> +1 Heal </strong> when Healing you.",
            "cardTooltip": "Other heroes gain <strong> +1 Heal </strong> when Healing you."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 Max Morale. <br> <br> Whenever you take damage, gain 1 <strong> Focus </strong> of your choice.",
            "cardTooltip": "+1 <strong> Morale. </strong> Gain 1 <strong> Focus </strong> when damaged."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you take damage, you may <strong> Jab. </strong>",
            "cardTooltip": "Whenever you take damage, you may <strong> Jab. </strong>"
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 max Morale. <br> <br> You gain <strong> Force </strong> equal to half the amount of Morale you are missing (round up).",
            "cardTooltip": "+1 <strong> Morale. Force </strong> bonus of half your damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: The marked foe can't use prepped actions unless they take 1 damage.",
            "cardTooltip": "Threatening Mark: Marked foe can't use prepped actions unless they take 1 damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: The marked foe can't engage a hero who is not in their zone unless they take 1 damage.",
            "cardTooltip": "Threatening Mark: Marked foe can't ranged unless they take 1 damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: The marked foe can't Step unless they take 1 damage.",
            "cardTooltip": "Threatening Mark: Marked foe can't Step unless they take 1 damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: The marked foe's next engagement is <strong> Gentle </strong> unless they take 1 damage.",
            "cardTooltip": "Threatening Mark: Marked foe's next is Gentle unless they take 1 damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: When you apply your Mark, you may <strong> Hustle </strong> the foe unless they take 1 damage.",
            "cardTooltip": "Threatening Mark: When mark applied, Hustle foe unless they take 1 damage."
        },
        {
            "cardTitle": "Bold",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "6",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Threatening Mark Option: When the marked foe would start their turn, if you haven't taken a turn yet this round, you may seize initiative. (Unlike most seizes, this one can be used multiple times.)",
            "cardTooltip": "Threatening Mark: Can seize from marked foe."
        },
        {
            "cardTitle": "Direct",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 <strong> Force </strong> when making technique engagements.",
            "cardTooltip": "Gain +1 Force with Technique engagements."
        },
        {
            "cardTitle": "Direct",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 <strong> Force </strong> when making technique engagements.",
            "cardTooltip": "Gain a total of +2 Force with technique engagements."
        },
        {
            "cardTitle": "Direct",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 to Gathering rolls.",
            "cardTooltip": "Gain +1 to Gathering rolls."
        },
        {
            "cardTitle": "Direct",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 <strong> Force </strong> when making technique engagements.",
            "cardTooltip": "Gain a total of +3 Force with technique engagements."
        },
        {
            "cardTitle": "Direct",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 to Gathering rolls.",
            "cardTooltip": "Gain a total of +2 to Gathering rolls."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Gain a persistent prep called \"Sentinel\" : 'When an ally you can sense is engaged, after you know the total roll, you may use this prep to give the ally +1 <strong> Composure </strong> against that engagement.'",
            "cardTooltip": "Sentinel persistent prep: When ally is engaged, give +2 <strong> Composure. </strong>"
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Gain a persistent prep called \"Sentinel\" : 'When an ally you can sense is engaged, after you know the total roll, you may use this prep to give the ally +1 <strong> Composure </strong> against that engagement.'",
            "cardTooltip": "Sentinel persistent prep: When ally is engaged, give +2 <strong> Composure. </strong>"
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "When you use Sentinel, you may <strong> Hustle </strong> the triggering foe after their engagement resolves.",
            "cardTooltip": "Sentinel <strong> Hustles </strong> the triggering foe."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you grant a <strong> Composure </strong> bonus to yourself or an ally, increase the amount of the bonus by 1.",
            "cardTooltip": "Increase all <strong> Composure </strong> bonuses you grant by 1."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "When you use Sentinel, if the foe was engaging your ally with a <strong> Jab, </strong> cancel the <strong> Jab </strong> instead of giving your ally a <strong> Composure </strong> bonus against it.",
            "cardTooltip": "Sentinel can cancel a foe's <strong> Jab. </strong>"
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You can use your prep action during your turn to choose a foe, and prep the following action: 'If that foe engages while in your zone, you may cancel their engagement unless it targets you.'",
            "cardTooltip": "Can prep: If target foe in your zone engages another hero, cancel it."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "When you use Sentinel, in addition to granting the ally the <strong> Composure </strong> bonus, the ally gains +2 <strong> Force </strong> to their next engagement.",
            "cardTooltip": "Sentinel additionally grants triggering ally +2 <strong> Force.</strong>"
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain a persistent prep: 'When an ally is engaged, if the ally is not in your zone, you may <strong> Hustle </strong> one zone closer to the engaged ally.'",
            "cardTooltip": "Persistent prep: When ally is engaged, <strong> Hustle </strong> towards them."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain an extra Sentinel persistent prep each turn. (Thus you have two uses of Sentinel each round.) You cannot use Sentinel more than once per turn.",
            "cardTooltip": "Sentinel can be used twice a round."
        },
        {
            "cardTitle": "Guarded",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "At the start of your turn, choose any ally you can sense. That ally regains 1 Morale.",
            "cardTooltip": "Start of your turn, heal any ally for 1."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You may expend a prep action to gain a hasten action.",
            "cardTooltip": "You may spend prep to gain a hasten."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain a persistent prep: When you are engaged, <strong> Jab </strong> the engaging foe.",
            "cardTooltip": "Persistent prep: When you're engaged, <strong> Jab </strong> engaging foe."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain an initiative seize. Whenever you seize, you may <strong> Hustle. </strong>",
            "cardTooltip": "Gain a seize. <strong> Hustle </strong> when you seize."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain an initiative seize. Whenever you seize, you may <strong> Jab. </strong>",
            "cardTooltip": "Gain a seize. <strong> Jab </strong> when you seize."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 <strong> Force </strong> for each zone you enter. This bonus is cumulative, and expires at the start of your turn.",
            "cardTooltip": "+1 <strong> Force </strong> when you move, til start of your turn. Cumulative."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You can <strong> Combine </strong> a technique onto your <strong> Jabs.",
            "cardTooltip": "You can <strong> Combine </strong> a technique onto your <strong> Jabs.</strong>"
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain +1 <strong> Composure </strong> for each zone you enter. This bonus is cumulative, and expires at the start of your turn.",
            "cardTooltip": "+1 <strong> Composure </strong> when you move, til start of your turn. Cumulative."
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You may <strong> Surge </strong> each of your <strong> Jabs. </strong> (Choose a type of <strong> Focus </strong> when you <strong> Surge, </strong> and all <strong> Focus </strong> spent must be of that type.)",
            "cardTooltip": "You may <strong> Surge Jabs.</strong>"
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "At the beginning of your turn, after the expire step, you may <strong> Hustle. </strong>",
            "cardTooltip": "At beginning of your turn, you may <strong> Hustle.</strong>"
        },
        {
            "cardTitle": "Pugilist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you enter a zone, you may <strong> Jab.</strong>",
            "cardTooltip": "Whenever you enter a zone, you may <strong> Jab.</strong>"
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: You gain an initiative seize. When you seize, you may pass to another character instead of taking a turn yourself.",
            "cardTooltip": "Gain a seize. You may pass to another when you seize."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: You gain a persistent prep: After any character rolls the die for an engagement, you may force them to re-roll the die and use the new result.",
            "cardTooltip": "Persistent prep: Force anyone to reroll an engagement."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Once per turn, you may pay one <strong> Morale </strong> to gain two <strong> Focus </strong> of your choice. This does not cost an action.",
            "cardTooltip": "Once per turn, take 1 damage to gain 2 <strong> Focus.</strong>"
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Whenever you <strong> Surge, </strong> you may use any one type of <strong> Focus </strong> (instead of using <strong> Focus </strong> of the technique's type).",
            "cardTooltip": "<strong>Surge </strong> with any type of <strong> Focus.</strong>"
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Once per encounter, you may use a non-Calling technique you don't have, that an ally has. This uses the same action as the technique normally requires. This does not count as the ally using that technique.",
            "cardTooltip": "Once per encounter, use a technique known by an ally."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "6",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Once per turn, you may spend a prep action to gain a hasten action, or spend a hasten action to gain a prep action.",
            "cardTooltip": "Once per turn, spend prep to gain hasten or vice versa."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "7",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Once per turn, you may pay any three <strong> Focus, </strong> to gain two <strong> Focus </strong> of any type. This does not cost an action.",
            "cardTooltip": "Once per turn, spend 3 <strong> Focus <strong> to gain 2 <strong> Focus.</strong>"
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "8",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: Once per encounter, you can spend your hasten action to <strong> Hustle </strong> any character, then <strong> Hustle </strong> any character.",
            "cardTooltip": "Once per encounter, use hasten action to <strong> Hustle <strong> any character, then do it again."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "9",
            "cardActionLetter": "o",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "Resourceful option: During your Gathering roll, you can apply the three die rolls to the three Virtues in whatever way you wish, instead of rolling for each in turn. ",
            "cardTooltip": "Apply Gathering dice to the Virtues as you wish."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "s",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "SUPREME Resourceful option: At the start of your turn, you may gain 1 <strong> Focus </strong> of the type of your choice.",
            "cardTooltip": "At start of turn, gain 1 <strong> Focus.</strong>"
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "s",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "SUPREME Resourceful option: You can use your Aid action to choose an ally that hasn't acted yet this round. That ally immediately takes a Main action. That ally does not get a Main action during their next turn.",
            "cardTooltip": "Use your Aid action to cause an ally to use up their Main action early."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "s",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "SUPREME Resourceful option: You may use your once-per-encounter abilities (such as initiative seizes, bearing abilities or Calling abilities) one extra time per encounter.",
            "cardTooltip": "Use once-per-encounter abilities one extra time."
        },
        {
            "cardTitle": "Resourceful",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "s",
            "bearingoption": "option",
            "inspirationCostToBuy": "2",
            "cardBody": "SUPREME Resourceful option: Gain any two standard Resourceful options.",
            "cardTooltip": "Gain any two normal Resourceful options."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain an initiative seize. The character you seize from doesn't take their turn, but counts as starting and ending their turn, for the purposes of effects expiring.",
            "cardTooltip": "Gain a seize. The character you seize from starts/ends turn without taking it."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain a persistent prep: 'When a foe in your zone has a prepped action trigger, you may use this prep to cancel their prepped action. <br> Or, when a foe in your zone <strong> Jabs, </strong> you may use this prep to choose the target of their <strong> Jab. </strong> (The new target must be legal. You cannot force the foe to <strong> Jab </strong> itself.)'",
            "cardTooltip": "Persistent prep: Cancel a foe's prep OR redirect their <strong> Jab.</strong>"
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you would be <strong> Hustled, </strong> you may take a hasten action instead.",
            "cardTooltip": "Whenever you would be <strong> Hustled, </strong> you may take a hasten action instead."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain a persistent prep: When you're engaged, you may <strong> Jab </strong> the triggering foe.",
            "cardTooltip": "Persistent prep: When engaged, you may <strong> Jab <strong> the engaging foe."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain an Aura: 'Foes in your zone have - 1 <strong> Force </strong> and -1 <strong> Composure.' </strong>",
            "cardTooltip": "Aura: Foes in your zone have -1 <strong> Force </strong> and <strong> Composure.</strong>"
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you <strong> Jab </strong> a foe and it is not your turn, you may have that foe <strong> Jab </strong> itself instead.",
            "cardTooltip": "When you <strong> Jab </strong> off-turn, may have foe <strong> Jab </strong> itself instead."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Whenever you make a technique engagement, you may choose to make that engagement <strong> Gentle. </strong> If you do, then the technique costs 2 less <strong> Focus. </strong>",
            "cardTooltip": "May make an engagement <strong> Gentle </strong> so it costs 2 less <strong> Focus. </strong>"
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "4",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You can take an extra prep action each turn.",
            "cardTooltip": "Gain an extra prep action each turn."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "Your engagements don't count as you engaging the foe unless you want them to. You can't trigger foes' prepped actions unless you want to. <br> <br> Foes can't count you as being in their zone even if you are (for purposes of the foe's Auras, Turfs, and area attacks).",
            "cardTooltip": "You don't count as engaging, don't trigger enemy preps, don't count as being in foe's zone."
        },
        {
            "cardTitle": "Subtle",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "5",
            "cardActionLetter": "B",
            "bearingoption": "text",
            "inspirationCostToBuy": "2",
            "cardBody": "You gain a persistent prep: After a foe makes an engagement in your zone, and all reactions to its engagement resolve, use this prep to force the foe to end its turn. (The foe can take no further actions this turn.)",
            "cardTooltip": "Persistent prep: After foe engages in your zone, end their turn."
        },
        {
            "cardTitle": "Advance",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Before engaging, you may <strong> Hustle. </strong> <br> <br> After engaging, you may choose a hero in a zone adjacent to yours, and <strong> Hustle </strong> that hero into your zone.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Before engaging, <strong> Hustle </strong> self. After engaging, <strong> Hustle </strong> ally to you."
        },
        {
            "cardTitle": "Aggravate",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +2. <br> <br> After engaging: The target gains +2 <strong> Force </strong> until the beginning of your next turn.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage with +2. Foe gains +2 <strong> Force. </strong>"
        },
        {
            "cardTitle": "Aim",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": "The next engagement you make this turn gains <strong> +1 Range. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "The next engagement you make this turn gains <strong> +1 Range. </strong>"
        },
        {
            "cardTitle": "Anticipation",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Prep this action: After any character you can sense rolls an engagement, you may use this prep to force them to reroll their engagement and keep the new result.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Prep: Force any character to reroll engagement."
        },
        {
            "cardTitle": "Ameliorate",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose an ally. You may end any one status on that ally. <br> <br> <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "End status on one ally, then <strong> Heal </strong> them."
        },
        {
            "cardTitle": "Appeal",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +1 Range. <br> <br> After engaging, <strong> Hustle </strong> the target closer to you.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage with +1 <strong> Range. </strong> <strong> Hustle </strong> target toward you."
        },
        {
            "cardTitle": "Assist",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Compassion] <br> <br> (Calling ability: OPE, No Action) <br> <br> Use this ability when an ally rolls a 1 when making an engagement. <br> <br> Roll a d6, and add the result to the triggering ally's <strong> Force </strong> for this engagement.",
            "cardType": "technique",
            "techIsCalling": "Compassion",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "When engaging ally rolls 1, add 1d6."
        },
        {
            "cardTitle": "Blunt",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage your target. The next time your target engages before the start of your next turn, prevent all non-damage effects of the engagement. <br> <br> (Damage from the target’s engagement happens normally but side effects, such as stat penalties or <strong> Hustles, </strong> are prevented.)",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. Prevent non-damage effects of target's next engagement."
        },
        {
            "cardTitle": "Bouy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Heal </strong> an ally. That ally gains +3 <strong> Composure </strong> for the next engagement against them before your next turn.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong> Heal </strong> an ally. They get +3 <strong> Composure. </strong>"
        },
        {
            "cardTitle": "Brace",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Spend any amount of Morale, and choose another hero that can sense you. The chosen hero gains a bonus to <strong> Composure </strong> until the start of your next turn. The bonus is four times the amount of Morale you spent.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Spend your Morale to give an ally +4 <strong> Composure </strong> per Morale spent."
        },
        {
            "cardTitle": "Bulwark",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the beginning of your next turn, you gain an <strong> Aura: </strong> Heroes in your zone gain +2 <strong> Composure. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Until the start of your next turn, heroes in your zone have +2 <strong> Composure. </strong>"
        },
        {
            "cardTitle": "Calm",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Compassion] <br> <br> (Calling ability: OPE, No Action) <br> <br> Use this ability when a foe engages an ally you can see. <br> <br> Roll a d6, and add the result to the triggering ally's <strong> Composure </strong> against this engagement.",
            "cardType": "technique",
            "techIsCalling": "secCompassion",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "When ally engaged, grant +1d6 <strong> Composure.</strong>"
        },
        {
            "cardTitle": "Caper",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Clever/Courage Calling] <br> <br> After engaging, you may <strong> Hustle </strong> any character in an adjacent zone into your zone, and then you may <strong> Hustle </strong> any character in your zone (including yourself) out of the zone.",
            "cardType": "technique",
            "techIsCalling": "Clever/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "After engaging, <strong> Hustle </strong> someone into zone, then <strong> Hustle </strong> someone out of zone."
        },
        {
            "cardTitle": "Cavalier",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Courage Calling] <br> <br> You gain a bonus to this engagement equal to the base <strong> Force </strong> bonus of the target foe.",
            "cardType": "technique",
            "techIsCalling": "Courage/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Gain bonus equal to foe's <strong> Force </strong> bonus."
        },
        {
            "cardTitle": "Culmination",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage. If you use this technique against a foe that has triggered one of your prep actions during this encounter, then you gain an extra +1 <strong> Force </strong> for each point you spend to <strong> Surge. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "If you engage a foe who's triggered your prep, +1 per <strong> Surge.</strong>"
        },
        {
            "cardTitle": "Dauntless",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Courage] <br> <br> (Calling ability: OPE, No Action) <br> <br> Use this ability when you would be able to use a hasten action. <br> <br> <strong> Hustle. </strong>",
            "cardType": "technique",
            "techIsCalling": "Courage",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "During your turn, <strong> Hustle </strong> yourself."
        },
        {
            "cardTitle": "Discretion",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Clever] <br> <br> (Calling ability: OPE, No Action) <br> <br> You may use this ability when your turn begins, and another character could act instead. <br> <br> The turn is passed to a valid character of your choice instead of you.",
            "cardType": "technique",
            "techIsCalling": "secClever",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "When turn is passed to you, pass to another instead."
        },
        {
            "cardTitle": "Dogged",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Hustle. </strong> <br> <br> If there are no heroes or foes in your new zone, <strong> Hustle </strong> again. <br> <br> If there is at least one foe in your new zone, regain one Morale.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Hustle, </strong> then <strong> Hustle </strong> again if new zone empty."
        },
        {
            "cardTitle": "Empower",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "This engagement deals half damage (round up). <br> <br> After engaging: Choose another hero. They gain a bonus to their next engagement before your next turn, equal to 4 times the damage dealt with this engagement.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Deal half damage. Give ally <strong> Force </strong> bonus equal to 4 times damage dealt."
        },
        {
            "cardTitle": "Exertion",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Before engaging: You lose one point of Morale. <br> <br> Engage with +3. <br> <br> Special: This technique counts as a Courage technique, and can be <strong> Surged </strong> and <strong> Combined, </strong> even though it costs no <strong> Focus. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Pay one Morale to engage with +3."
        },
        {
            "cardTitle": "Extend",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose an ally and <strong> Heal. </strong> You may choose a second ally and <strong> Heal </strong> them for the same amount the first one was healed for, without paying any <strong> Focus </strong> for the second ally.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong> Heal </strong> two allies for the same amount."
        },
        {
            "cardTitle": "Hamper",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the start of your next turn, the target cannot move to another zone with their hasten action as normal. <br> <br> They may use their main action to move to a different zone, rather than their hasten action.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Foe must use Main to step."
        },
        {
            "cardTitle": "Hypervigilant",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Prep this action: If a foe engages you, you may <strong> Jab </strong> it after its engagement resolves. <br> <br> If this prep expires, you lose 1 Morale.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Prep: If engaged, <strong> Jab. </strong> If prep expires, take 1 damage."
        },
        {
            "cardTitle": "Incite",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Clever/Compassion Calling] <br> <br> After engaging, until the start of your next turn, whenever you would <strong> Jab, </strong> you may instead have each ally <strong> Jab </strong> a foe of their choice.",
            "cardType": "technique",
            "techIsCalling": "Clever/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "After engaging, if you would <strong> Jab, </strong> instead allies <strong> Jab.</strong>"
        },
        {
            "cardTitle": "Indignation",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Compassion Calling ] <br> <br> Engage with +1 for each point of Morale you have healed to an ally this encounter. You cannot gain more than +10 in this way.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "+1 <strong> Force </strong> for each point you've healed allies."
        },
        {
            "cardTitle": "Leverage",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with a bonus equal to the total number of Traits that have been revealed this encounter.",
            "cardType": "technique",
            "techIsCalling": true,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage with a bonus equal to the total number of Traits that have been revealed this encounter."
        },
        {
            "cardTitle": "Remedy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Heal </strong> an ally. If that ally is in your zone, you have +1 <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong> Heal </strong> ally. Heal + 1 if they're in your zone."
        },
        {
            "cardTitle": "Mercy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +6. If this engagement does not vanquish the target, then this engagement becomes <strong> Gentle </strong> and the target’s next engagement becomes <strong> Gentle. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage +6. If target not vanquished, deal no damage, and target Gentled."
        },
        {
            "cardTitle": "Moxie",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Courage] <br> <br> (Calling ability: OPE, No Action) <br> <br> Use this ability when you could use any other initiative seize. <br> <br> Seize initiative.",
            "cardType": "technique",
            "techIsCalling": "secCourage",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Initiative seize."
        },
        {
            "cardTitle": "Onrush",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage, and after engaging: If you and the target are in the same zone, you must <strong> Hustle </strong> the target into another zone.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. If in target's zone, you may <strong> Hustle </strong> them."
        },
        {
            "cardTitle": "Outmaneuver",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Clever/Clever Calling] <br> <br> You may choose to lose any number of actions you have prepped. (Those actions are no longer prepped, but do not count as expiring.) You gain +2 to the engagement for each prep action you lose this way.",
            "cardType": "technique",
            "techIsCalling": "Clever/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. You may spend preps to gain +2 per."
        },
        {
            "cardTitle": "Patience",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "You gain +2 to all your gathering rolls at the start of your next turn. <br> <br> Do not engage as part of this technique. <br> <br> Since there is no engagement, you cannot <strong> Surge </strong> or <strong> Combine </strong> this technique.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Gain +2 to next Gather. No engagement."
        },
        {
            "cardTitle": "Prediction",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the start of your next turn, all heroes gain +2 <strong> Force </strong> with <strong> Jabs, </strong> and all foes suffer –2 <strong> Force </strong> with <strong> Jabs. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Heroes +2 to <strong> Jabs, </strong> foes -2 to <strong> Jabs.</strong>"
        },
        {
            "cardTitle": "Ramify",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Clever Calling ] <br> <br> You may target one extra foe with this engagement.",
            "cardType": "technique",
            "techIsCalling": "Courage/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Target an extra foe with this engagement."
        },
        {
            "cardTitle": "Relentless",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage. You gain +3 if you have engaged the target since the start of your last turn. <br> <br> After engaging: You gain +3 with the next engagement you make against the target before the end of your next turn.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. +3 if you engaged them last turn. +3 if you engage them next turn."
        },
        {
            "cardTitle": "Scrutinize",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Clever] <br> <br> (Calling ability: OPE, No Action) <br> <br> Use this ability when you would be able to use a prep action. <br> <br> Choose and learn any one trait of a foe.",
            "cardType": "technique",
            "techIsCalling": "Clever",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Learn a trait for free."
        },
        {
            "cardTitle": "Sleight",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +1 <strong> range. </strong> <br> <br> After engaging: <strong> Hustle </strong> the target.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Engage with +1 range, and <strong> Hustle </strong> the target."
        },
        {
            "cardTitle": "Spontaneity",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": " <strong> Jab </strong> a foe. <br> <br> (This technique counts as a <strong> Jab, </strong> so it cannot be <strong> Surged </strong> or <strong> Combined </strong> unless an effect specifically allows you to <strong> Surge </strong> or <strong> Combine </strong> <strong> Jabs. </strong> )",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Jab.</strong>"
        },
        {
            "cardTitle": "Triage",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose either <strong> Force </strong> or <strong> Composure, </strong> and choose an ally. The ally gains +2 to the chosen stat until the start of your next turn. <br> <br> <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> one ally. They gain either +2 <strong> Force </strong> or +2 <strong> Composure.</strong>"
        },
        {
            "cardTitle": "Spur",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Heal </strong> an ally. <strong> Hustle </strong> that ally unless they have already been <strong> Hustled </strong> this round.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> an ally. <strong> Hustle </strong> them unless they've been <strong> Hustled </strong> this round."
        },
        {
            "cardTitle": "Stir",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Clever Calling] <br> <br> Make a <strong> Gentle </strong> engagement. <br> <br> After engaging, choose a hero, and choose a foe. Until the start of your next turn, the chosen hero gains a <strong> Force </strong> bonus, and the chosen foe takes a <strong> Force </strong> penalty, equal to 4 times the gentled damage.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage <strong> Gentle. </strong> Hero gains +4 <strong> Force </strong> per gentled, foe gets -4 <strong> Force </strong> per gentled."
        },
        {
            "cardTitle": "Strengthen",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose an ally. That ally gains +3 <strong> Force </strong> to the next engagement they make before your next turn. <br> <br> <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> an ally. They gain +3 to their next engagement."
        },
        {
            "cardTitle": "Strive",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Compassion Calling] <br> <br> Before engaging, you may spend any amount of Morale, up to your current amount. <br> <br> Engage with +2 for each Morale spent.",
            "cardType": "technique",
            "techIsCalling": "Courage/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. You may spend <strong> Morale </strong> to gain +2 per."
        },
        {
            "cardTitle": "Ward",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Courage Calling ] <br> <br> Engage. After engaging, you gain this Aura effect until the end of your next turn: When a foe makes an engagement while in your zone, the target of their engagement may <strong> Jab </strong> that foe.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage and gain Aura: If ally in your zone is engaged, ally may <strong> Jab </strong> engaging foe."
        },
        {
            "cardTitle": "Watchful",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Prep this action: When another hero you can sense is engaged, you may grant them +2 <strong> Composure </strong> against that engagement.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Prep: Give engaged ally +2 <strong> Composure </strong> once."
        },
        {
            "cardTitle": "Courageous Outlook",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Courage </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Courage focus each Gathering."
        },
        {
            "cardTitle": "Compassion Outlook",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Compassion </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Clever focus each Gathering."
        },
        {
            "cardTitle": "Clever Outlook",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Clever </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Clever focus each Gathering."
        },
        {
            "cardTitle": "Hopeful Outlook",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> If you lost any Hope last encounter, then you must choose Hopeful Outlook this encounter. <br> <br> Hopeful Outlook provides no bonus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose this Outlook if you lost Hope last encounter. <br> This outlook gives no bonus."
        },
        {
            "cardTitle": "Z Character Sheet",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "Character sheet will be updated on the printed images automatically.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Character sheet, populated when printing"
        },
        {
            "cardTitle": "Z Stats Sheet",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "Character sheet will be updated on the printed images automatically.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Character sheet, populated when printing"
        }
     ]
