
virtuesJson = [
{
            "cardTitle": "Straightforward",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +3 Force with main action engagements.",
            "cardTooltip": "You gain +3 Force with main action engagements."
        },
        {
            "cardTitle": "Straightforward",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +3 Force with main action engagements.",
            "cardTooltip": "You gain +3 Force with main action engagements."
        },
        {
            "cardTitle": "Straightforward",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "cardActionLetter": "A",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +3 Force with main action engagements.",
            "cardTooltip": "You gain +3 Force with main action engagements."
        },
        {
            "cardTitle": "Headstrong",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Gain an initiative sieze (OPE). When you use this seize, you may either Step or Jab.",
            "cardTooltip": "Gain an initiative sieze (OPE). When you use this seize, you may either Step or Jab."
        },
        {
            "cardTitle": "Headstrong",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "When you take damage from an enemy engagement, you may either Step or Jab.",
            "cardTooltip": "When you take damage from an enemy engagement, you may either Step or Jab."
        },
        {
            "cardTitle": "Headstrong",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +3 Sheer Force.",
            "cardTooltip": "You gain +3 Sheer Force."
        },
        {
            "cardTitle": "Scarred Soldier",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +4 Sheer Force, but you gain Early. (No character without Early can be chosen to act until all Early characters have acted.) ",
            "cardTooltip": "You gain +4 Sheer Force, but you gain Early. (No character without Early can be chosen to act until all Early characters have acted.) "
        },
        {
            "cardTitle": "Scarred Soldier",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +1 Composure, but you are Conspicuous. (Foes can't target another hero in your zone if they could target you instead.)",
            "cardTooltip": "You gain +1 Composure, but you are Conspicuous. (Foes can't target another hero in your zone if they could target you instead.)"
        },
        {
            "cardTitle": "Scarred Soldier",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +3 maximum Morale. Also, at the start of each of your turns, you regain 1 Morale.",
            "cardTooltip": "You gain +3 maximum Morale. Also, at the start of each of your turns, you regain 1 Morale."
        },
        {
            "cardTitle": "Punchy Princess",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You may Seize once each round. If you seize from a foe in your zone, you may Jab them. ",
            "cardTooltip": "You may Seize once each round. If you seize from a foe in your zone, you may Jab them. "
        },
        {
            "cardTitle": "Punchy Princess",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You may Jab whenever you enter a zone. <br> <br> Also, once during each of your turns, you may pay 2 Focus to Hustle yourself one zone.",
            "cardTooltip": "You may Jab whenever you enter a zone. <br> <br> Also, once during each of your turns, you may pay 2 Focus to Hustle yourself one zone."
        },
        {
            "cardTitle": "Punchy Princess",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You and your allies gain +2 Force with Jabs.",
            "cardTooltip": "You and your allies gain +2 Force with Jabs."
        },
        {
            "cardTitle": "Overprotective Pilgrim",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "option",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain Cheerleader +2. (When you use your Aid action to heal an ally, the first focus spent on the heal is free.) <br> <br> Also, whenever you Cheer an ally whose current Morale is less than or equal to their max, you may heal them above their max. ",
            "cardTooltip": "You gain Cheerleader +2. (When you use your Aid action to heal an ally, the first focus spent on the heal is free.) <br> <br> Also, whenever you Cheer an ally whose current Morale is less than or equal to their max, you may heal them above their max. "
        },
        {
            "cardTitle": "Overprotective Pilgrim",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "option",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever you Cheer an ally for 2 or more Morale, your next main action engagement before the start of your next turn deals extra damage equal to your Sheer Force.",
            "cardTooltip": "Whenever you Cheer an ally for 2 or more Morale, your next main action engagement before the start of your next turn deals extra damage equal to your Sheer Force."
        },
        {
            "cardTitle": "Overprotective Pilgrim",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "option",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever you Cheer an ally for 2 or more Morale, that ally gains +2 Composure until the start of your next turn.",
            "cardTooltip": "Whenever you Cheer an ally for 2 or more Morale, that ally gains +2 Composure until the start of your next turn."
        },
        {
            "cardTitle": "Fiery Dancer",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You gain +1 Range. Also, your Main action engagements gain Force equal to the number of zones away your target is.",
            "cardTooltip": "You gain +1 Range. Also, your Main action engagements gain Force equal to the number of zones away your target is."
        },
        {
            "cardTitle": "Fiery Dancer",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "After using your Main action to make an engagement, you may Jab with Range +2. This Jab gains Force equal to half the damage dealt by your engagement.",
            "cardTooltip": "After using your Main action to make an engagement, you may Jab with Range +2. This Jab gains Force equal to half the damage dealt by your engagement."
        },
        {
            "cardTitle": "Fiery Dancer",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "After you're engaged by a foe, you may Hustle yourself. Then, whether you Hustled or not, you may Jab at the engaging foe (provided they are in range) with a Force bonus equal to the damage dealt to you by their engagement.",
            "cardTooltip": "After you're engaged by a foe, you may Hustle yourself. Then, whether you Hustled or not, you may Jab at the engaging foe (provided they are in range) with a Force bonus equal to the damage dealt to you by their engagement."
        },
{
            "cardTitle": "Prophecy's Chosen",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You are Conspicuous. (Foes can't target another hero in your zone if they could target you instead.)  After any ally Cheers you, they gain 1 Pure Focus.",
            "cardTooltip": "You are Conspicuous. (Foes can't target another hero in your zone if they could target you instead.)  After any ally Cheers you, they gain 1 Pure Focus."
        },
        {
            "cardTitle": "Prophecy's Chosen",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You and any allies in the encounter gain +1 Force and +1 max Morale.",
            "cardTooltip": "You and any allies in the encounter gain +1 Force and +1 max Morale."
        },
        {
            "cardTitle": "Prophecy's Chosen",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "You and any allies in the encounter gain +1 Pure Focus during Gathering.",
            "cardTooltip": "You and any allies in the encounter gain +1 Pure Focus during Gathering."
        },
        {
            "cardTitle": "Martyr",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "At the start of round, before rolling, you may deal 1 damage to yourself to gain +1 Composure and Conspicuous until your next Gathering. <br> <br> Also, you gain 3 max Morale.",
            "cardTooltip": "At the start of round, before rolling, you may deal 1 damage to yourself to gain +1 Composure and Conspicuous until your next Gathering. <br> <br> Also, you gain 3 max Morale."
        },
        {
            "cardTitle": "Martyr",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "At the start of Gathering, before rolling, you may deal 1 Hope damage to yourself to gain 3 Pure Focus. <br> <br> Also, at the end of each encounter, you heal 1 Hope.",
            "cardTooltip": "At the start of Gathering, before rolling, you may deal 1 Hope damage to yourself to gain 3 Pure Focus. <br> <br> Also, at the end of each encounter, you heal 1 Hope."
        },
        {
            "cardTitle": "Martyr",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Anytime you take any amount of damage, for any reason, gain that amount of Pure Focus.",
            "cardTooltip": "Anytime you take any amount of damage, for any reason, gain that amount of Pure Focus."
        },
        {
            "cardTitle": "Chemist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever you Cheer an ally whose current morale is equal to their max, you may heal them above their max. Also, as long as at least one ally has current Morale higher than their max, you gain a Force bonus to main action engagements equal to your Sheer Force.",
            "cardTooltip": "Whenever you Cheer an ally whose current morale is equal to their max, you may heal them above their max. Also, as long as at least one ally has current Morale higher than their max, you gain a Force bonus to main action engagements equal to your Sheer Force."
        },
        {
            "cardTitle": "Chemist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever a foe is vanquished, you may immediately Cheer an ally. This Cheer does not cost an action, and gains Cheerleader +2.",
            "cardTooltip": "Whenever a foe is vanquished, you may immediately Cheer an ally. This Cheer does not cost an action, and gains Cheerleader +2."
        },
        {
            "cardTitle": "Chemist",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever you Cheer an ally, a second ally may choose to take one Morale damage (ignoring Composure). If they do, this Cheer gains Cheerleader +3, and the second ally gains +2 Force until the start of your next turn.",
            "cardTooltip": "Whenever you Cheer an ally, a second ally may choose to take one Morale damage (ignoring Composure). If they do, this Cheer gains Cheerleader +3, and the second ally gains +2 Force until the start of your next turn."
        },
        {
            "cardTitle": "Executioner",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "When engaging a foe that has already taken damage this round, add your Sheer Force to the engagement.",
            "cardTooltip": "When engaging a foe that has already taken damage this round, add your Sheer Force to the engagement."
        },
        {
            "cardTitle": "Executioner",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Anytime you could use a Main action, you may pay Morale to Jab. <br> <br> You may use this ability up to three times in one round. <br> <br> It costs 1 Morale the first time you Jab with this ability, 2 Morale the second time and 3 Morale the third time. <br> <br> Also: Whenever any engagement or Jab you make vanquishes a foe, you regain 3 Morale.",
            "cardTooltip": "Anytime you could use a Main action, you may pay Morale to Jab. <br> <br> You may use this ability up to three times in one round. <br> <br> It costs 1 Morale the first time you Jab with this ability, 2 Morale the second time and 3 Morale the third time. <br> <br> Also: Whenever any engagement or Jab you make vanquishes a foe, you regain 3 Morale."
        },
        {
            "cardTitle": "Executioner",
            "cardVirtue": "bearing",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "3",
            "bearingoption": "text",
            "inspirationCostToBuy": "3",
            "cardBody": "Whenever you engage or Jab a foe with less than half of its health remaining, deal extra damage equal to your Sheer Force.",
            "cardTooltip": "Whenever you engage or Jab a foe with less than half of its health remaining, deal extra damage equal to your Sheer Force."
        },
        {
            "cardTitle": "Rejuvenate",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Your next cheer this turn gains +2 Cheerleader.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Your next cheer this turn gains +2 Cheerleader."
        },
        {
            "cardTitle": "Bustle",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "After engaging, Hustle yourself or an ally.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "After engaging, Hustle yourself or an ally."
        },
        {
            "cardTitle": "Mercy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Add twice your Sheer Force to this engagement, but if it doesn't deal enough damage to Vanquish your foe, then this engagement becomes Gentle.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Add twice your Sheer Force to this engagement, but if it doesn't deal enough damage to Vanquish your foe, then this engagement becomes Gentle."
        },
        {
            "cardTitle": "Teamwork",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Add your Sheer Force to this engagement if you describe how you are incorporating an ally in this engagement. (This description is flavor.)",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Add your Sheer Force to this engagement if you describe how you are incorporating an ally in this engagement. (This description is flavor.)"
        },
        {
            "cardTitle": "Sacrifice",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "You may deal any amount of Morale damage to yourself. Gain a bonus equal to that amount, and one ally regains that much Morale. ",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "You may deal any amount of Morale damage to yourself. Gain a bonus equal to that amount, and one ally regains that much Morale. "
        },
        {
            "cardTitle": "Soften",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the start of your next turn, the target ",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Until the start of your next turn, the target "
        },
        {
            "cardTitle": "Cheerful",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Compassion] <br> <br> (Calling ability: Passive, Always on) <br> <br> You gain +2 <strong> Cheerleader. </strong> (first 2 Focus spent on a cheer/heal is free)",
            "cardType": "technique",
            "techIsCalling": "Compassion",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "You gain +2 <strong> Cheerleader. </strong> (first 2 Focus spent on a cheer/heal is free)"
        },
        {
            "cardTitle": "Tough",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "If you are at full Morale, add your Sheer Force to this engagement. Otherwise, recover 1 Morale.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "If you are at full Morale, add your Sheer Force to this engagement. Otherwise, recover 1 Morale."
        },
        {
            "cardTitle": "Rush",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Before engaging, Hustle yourself.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Before engaging, Hustle yourself."
        },
        {
            "cardTitle": "Rebound",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Add your Sheer Force to this engagement if you describe how you are incorporating a foe in this engagement. (This description is flavor.)",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Add your Sheer Force to this engagement if you describe how you are incorporating a foe in this engagement. (This description is flavor.)"
        },
        {
            "cardTitle": "Stand Out",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": "You are Conspicuous until the beginning of your next turn. ",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "You are Conspicuous until the beginning of your next turn. "
        },
        {
            "cardTitle": "Break Out",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Compassion] <br> <br> (Calling ability: OPE, No Action) <br> <br> Once per encounter, during your turn, you may Hustle any ally without using an action.",
            "cardType": "technique",
            "techIsCalling": "secCompassion",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "OPE <strong>Hustle</strong> Ally, no action cost."
        },
        {
            "cardTitle": "Jostle",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "After engaging, Hustle the target.",
            "cardType": "technique",
            "techIsCalling": "Clever/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Either before or after your engagement, <strong> Hustle </strong> all foes."
        },
        {
            "cardTitle": "Strive",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Courage Calling OPE] <br> <br> This engagement gains a <strong> Force </strong> bonus equal to twice the number of foes in your zone.",
            "cardType": "technique",
            "techIsCalling": "Courage/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Gains a <strong> Force </strong> bonus equal to twice the number of foes in your zone"
        },
        {
            "cardTitle": "Culmination",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage. If you use this technique against a foe that has triggered one of your prep actions during this encounter, then you gain an extra +1 <strong> Force </strong> for each point you spend to <strong> Surge. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "If you engage a foe who's triggered your prep, +1 per <strong> Surge.</strong>"
        },
        {
            "cardTitle": "Forceful",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Courage] <br> <br> (Calling ability: Passive, always on) <br> <br> You gain +1 <strong> Sheer Force. </strong>",
            "cardType": "technique",
            "techIsCalling": "Courage",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "You gain +1 <strong> Sheer Force. </strong>"
        },
        {
            "cardTitle": "Scrutinize",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Clever] <br> <br> (Calling ability: OPE, No Action) <br> <br> Once per encounter, during your turn, you may <strong> Study </strong> without using an action.",
            "cardType": "technique",
            "techIsCalling": "secClever",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "OPE during your turn, you may <strong> Study </strong> without using an action."
        },
        {
            "cardTitle": "Dogged",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Hustle. </strong> <br> <br> If there are no heroes or foes in your new zone, <strong> Hustle </strong> again. <br> <br> If there is at least one foe in your new zone, regain one Morale.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Hustle, </strong> then <strong> Hustle </strong> again if new zone empty."
        },
        {
            "cardTitle": "Empower",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "This engagement deals half damage (round up). <br> <br> After engaging: Choose another hero. They gain a bonus to their next engagement before your next turn, equal to 4 times the damage dealt with this engagement.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Deal half damage. Give ally <strong> Force </strong> bonus equal to 4 times damage dealt."
        },
        {
            "cardTitle": "Exertion",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Before engaging: You lose one point of Morale. <br> <br> Engage with +3. <br> <br> Special: This technique counts as a Courage technique, and can be <strong> Surged </strong> and <strong> Combined, </strong> even though it costs no <strong> Focus. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Pay one Morale to engage with +3."
        },
        {
            "cardTitle": "Extend",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose an ally and <strong> Heal. </strong> You may choose a second ally and <strong> Heal </strong> them for the same amount the first one was healed for, without paying any <strong> Focus </strong> for the second ally.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong> Heal </strong> two allies for the same amount."
        },
        {
            "cardTitle": "Hamper",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the start of your next turn, the target cannot move to another zone with their hasten action as normal. <br> <br> They may use their main action to move to a different zone, rather than their hasten action.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Foe must use Main to step."
        },
        {
            "cardTitle": "Hypervigilant",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Prep this action: If a foe engages you, you may <strong> Jab </strong> it after its engagement resolves. <br> <br> If this prep expires, you lose 1 Morale.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Prep: If engaged, <strong> Jab. </strong> If prep expires, take 1 damage."
        },
        {
            "cardTitle": "Lock Step",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "0",
            "cardBody": "[Clever/Compassion Calling] <br> <br> Either before or after your engagement, <strong> Hustle </strong> yourself and all allies.",
            "cardType": "technique",
            "techIsCalling": "Clever/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Either before or after your engagement, <strong> Hustle </strong> yourself and all allies."
        },
        {
            "cardTitle": "Salvation",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Compassion Calling OPE] <br> <br> Engage, then perform a <strong> cheer </strong> with a <strong> cheerleader </strong> bonus equal to the damage dealt.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage, then perform a <strong> cheer </strong> with a <strong> cheerleader </strong> bonus equal to the damage dealt."
        },
        {
            "cardTitle": "Leverage-old",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with a bonus equal to the total number of Traits that have been revealed this encounter.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage with a bonus equal to the total number of Traits that have been revealed this encounter."
        },
        {
            "cardTitle": "Remedy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Heal </strong> an ally. If that ally is in your zone, you have +1 <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong> Heal </strong> ally. Heal + 1 if they're in your zone."
        },
        {
            "cardTitle": "Mercy",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +6. If this engagement does not vanquish the target, then this engagement becomes <strong> Gentle </strong> and the target’s next engagement becomes <strong> Gentle. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage +6. If target not vanquished, deal no damage, and target Gentled."
        },
        {
            "cardTitle": "Poke",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Secondary Courage] <br> <br> (Calling ability: OPE, No Action) <br> <br> Once per encounter, during your turn, you may <strong> Jab </strong> without using an action.",
            "cardType": "technique",
            "techIsCalling": "secCourage",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Once per encounter, during your turn, you may Jab without using an action."
        },
        {
            "cardTitle": "Onrush",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage, and after engaging: If you and the target are in the same zone, you must <strong> Hustle </strong> the target into another zone.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. If in target's zone, you may <strong> Hustle </strong> them."
        },
        {
            "cardTitle": "Leverage",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Clever/Clever Calling OPE] <br> <br> Learn all traits of your target. If all the foe's traits are known, add your Sheer Force.",
            "cardType": "technique",
            "techIsCalling": "Clever/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Learn all traits of your target. If all the foe's traits are known, add your Sheer Force."
        },
        {
            "cardTitle": "Patience",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "You gain +2 to all your gathering rolls at the start of your next turn. <br> <br> Do not engage as part of this technique. <br> <br> Since there is no engagement, you cannot <strong> Surge </strong> or <strong> Combine </strong> this technique.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Gain +2 to next Gather. No engagement."
        },
        {
            "cardTitle": "Prediction",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Until the start of your next turn, all heroes gain +2 <strong> Force </strong> with <strong> Jabs, </strong> and all foes suffer –2 <strong> Force </strong> with <strong> Jabs. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Heroes +2 to <strong> Jabs, </strong> foes -2 to <strong> Jabs.</strong>"
        },
        {
            "cardTitle": "Repel",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Clever Calling OPE] <br> <br> Once per Encounter <br> <br> Until the end of your next turn, whenever a foe enters or leaves your zone, you may <strong> Jab </strong> that foe.",
            "cardType": "technique",
            "techIsCalling": "Courage/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Until the end of your next turn, whenever a foe enters or leaves your zone, you may <strong> Jab </strong> that foe."
        },
        {
            "cardTitle": "Relentless",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage. You gain +3 if you have engaged the target since the start of your last turn. <br> <br> After engaging: You gain +3 with the next engagement you make against the target before the end of your next turn.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Engage. +3 if you engaged them last turn. +3 if you engage them next turn."
        },
        {
            "cardTitle": "Focused",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "0",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "0",
            "cardBody": "[Primary Clever] <br> <br> (Calling ability: Passive, always on) <br> <br> You gain 1 bonus <strong> Pure Focus </strong> during gathering phase.",
            "cardType": "technique",
            "techIsCalling": "Clever",
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "You gain 1 bonus <strong> Pure Focus </strong> during gathering phase."
        },
        {
            "cardTitle": "Sleight",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2",
            "cardActionLetter": "M",
            "inspirationCostToBuy": "1",
            "cardBody": "Engage with +1 <strong> range. </strong> <br> <br> After engaging: <strong> Hustle </strong> the target.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Engage with +1 range, and <strong> Hustle </strong> the target."
        },
        {
            "cardTitle": "Spontaneity",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "H",
            "inspirationCostToBuy": "1",
            "cardBody": " <strong> Jab </strong> a foe. <br> <br> (This technique counts as a <strong> Jab, </strong> so it cannot be <strong> Surged </strong> or <strong> Combined </strong> unless an effect specifically allows you to <strong> Surge </strong> or <strong> Combine </strong> <strong> Jabs. </strong> )",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Jab.</strong>"
        },
        {
            "cardTitle": "Triage",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose either <strong> Force </strong> or <strong> Composure, </strong> and choose an ally. The ally gains +2 to the chosen stat until the start of your next turn. <br> <br> <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> one ally. They gain either +2 <strong> Force </strong> or +2 <strong> Composure.</strong>"
        },
        {
            "cardTitle": "Spur",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "<strong> Heal </strong> an ally. <strong> Hustle </strong> that ally unless they have already been <strong> Hustled </strong> this round.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> an ally. <strong> Hustle </strong> them unless they've been <strong> Hustled </strong> this round."
        },
        {
            "cardTitle": "Ward",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Clever Calling OPE] <br> <br> Until the start of your next turn, whenever an ally is engaged, that ally may <strong> Jab </strong> their attacker.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Clever",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Until the start of your next turn, whenever an ally is engaged, that ally may <strong> Jab </strong> their attacker."
        },
        {
            "cardTitle": "Strengthen",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "A",
            "inspirationCostToBuy": "1",
            "cardBody": "Choose an ally. That ally gains +3 <strong> Force </strong> to the next engagement they make before your next turn. <br> <br> <strong> Heal. </strong>",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "<strong>Heal </strong> an ally. They gain +3 to their next engagement."
        },
        {
            "cardTitle": "Unflinching",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Courage/Compassion Calling OPE] <br> <br> Until the start of your next turn, you gain <strong> Conspicuous </strong> and +4 <strong> Composure. </strong>",
            "cardType": "technique",
            "techIsCalling": "Courage/Compassion",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "Until the start of your next turn, you gain <strong> Conspicuous </strong> and +4 <strong> Composure. </strong>"
        },
        {
            "cardTitle": "Baton Pass",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "2/0",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "[Compassion/Courage Calling OPE] <br> <br> This engagement becomes Gentle. Choose an ally. They gain a Force bonus to their next engagement equal to the gentled damage, plus twice your Sheer Force.",
            "cardType": "technique",
            "techIsCalling": "Compassion/Courage",
            "techissurgeable": true,
            "techIsDefault": false,
            "cardTooltip": "This engagement becomes Gentle. Choose an ally. They gain a Force bonus to their next engagement equal to the gentled damage, plus twice your Sheer Force."
        },
        {
            "cardTitle": "Watchful",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "P",
            "inspirationCostToBuy": "1",
            "cardBody": "Prep this action: When another hero you can sense is engaged, you may grant them +2 <strong> Composure </strong> against that engagement.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": false,
            "cardTooltip": "Prep: Give engaged ally +2 <strong> Composure </strong> once."
        },
        {
            "cardTitle": "Courageous Outlook",
            "cardVirtue": "Courage",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "E",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Courage </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Courage focus each Gathering."
        },
        {
            "cardTitle": "Compassion Outlook",
            "cardVirtue": "Compassion",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Compassion </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Clever focus each Gathering."
        },
        {
            "cardTitle": "Clever Outlook",
            "cardVirtue": "Clever",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> Each time you roll Gathering, gain 1 extra <strong> Clever </strong> focus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose 1 Outlook each encounter. <br> You gain +1 Clever focus each Gathering."
        },
        {
            "cardTitle": "Hopeful Outlook",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "You choose one <strong> Outlook </strong> at the beginning of each encounter, and gain its benefits until the encounter ends. <br> <br> If you lost any Hope last encounter, then you must choose Hopeful Outlook this encounter. <br> <br> Hopeful Outlook provides no bonus.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Choose this Outlook if you lost Hope last encounter. <br> This outlook gives no bonus."
        },
        {
            "cardTitle": "Z Character Sheet",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "Character sheet will be updated on the printed images automatically.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Character sheet, populated when printing"
        },
        {
            "cardTitle": "Z Stats Sheet",
            "cardVirtue": "Neutral",
            "cardPurchased": false,
            "cardExported": false,
            "cardNumber": "1",
            "cardActionLetter": "O",
            "inspirationCostToBuy": "0",
            "cardBody": "Character sheet will be updated on the printed images automatically.",
            "cardType": "technique",
            "techIsCalling": false,
            "techissurgeable": false,
            "techIsDefault": true,
            "cardTooltip": "Character sheet, populated when printing"
        }
     ]
